version: "3.8"

services:
  web:
    build: .
    ports:
      - "${PORT:-8888}:${PORT:-8888}"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PORT=${PORT:-8888}
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8888} --reload
    restart: always
