version: "3.8"

services:
  crawling:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8888 --reload
    restart: always
